### ISSUE TITLE
Create build for sync node

### ISSUE THREAD

**Issue by dimalit** [skalenetwork/skaled#1068]
1 Use latest release
2 Decide which features to add to it

**Comment by gannakulikova** [comment]
After the engineering discussion, the decision is to create beta version build for sync node release. cc @cstrangedk

**Comment by DmytroNazarenko** [comment]
https://github.com/skalenetwork/skaled/releases/tag/3.14.9-beta.4

**Comment by oleksandrSydorenkoJ** [comment]
skalenetwork/schain:3.14.9-beta.9 

Included to build 
1. Created skaled with read-only mode - catchup only 
2. Disabled transactions sending to sync-node
3. Disabled state root checks
4. Disabled block rotation
5. Enabled filestorage read-only (through Nginx)
6. Disabled Oracle-requests

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Skale legacy network

https://github.com/skalenetwork/skale-node/releases/tag/2.2.0-sync-node.0

https://github.com/skalenetwork/internal-support/blob/main/deployment-plans/skale-node-releases/23-sync-node-release-june-2022.md#qa-comment
