### ISSUE TITLE
Add a nice way to start from a local snapshot

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skaled#1069]
**Is your feature request related to a problem? Please describe.**

Currently it requires lots of tedious manual work to start from a local snapshot. 

**Describe the solution you'd like**

Add a nice user-friendly way to start from a local snapshot (such as a skaled flag)

**Comment by oleksandrSydorenkoJ** [comment]
this issue will be solved in the - 
https://github.com/skalenetwork/internal-support/issues/97 - skaled will try to start from the oldest snapshot on the schain with --download-snapshot option in cmd line
