### ISSUE TITLE
Add validation to SGX URL

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/skaled#1091]
some sgx urls were entered as

`http://host:port/` # lead to sgx connection error

instead of 

`http://host:port`

**Comment by oleksandrSydorenkoJ** [comment]
Checked on ima:1.3.0-develop.12
need to Verify on the stable version IMA-agent

[imaVerifyAndSign_verified.log](https://github.com/skalenetwork/skaled/files/8717943/imaVerifyAndSign_verified.log)

**Comment by sergiy-skalelabs** [comment]
included into 3.14.11-stable.0

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Skale Legacy network
schain:3.14.13-stable.2
ima:1.3.1-beta.0

[check_backslash_for_IMA.log](https://github.com/skalenetwork/skaled/files/8853942/check_backslash_for_IMA.log)
