### ISSUE TITLE
Empty or invalid resonse on calls to sakeld if enabled "Chainid transactions" check

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1122]
**Preconditions**
Active schains with enabled Chainid transactions check

**Versions**
skaled:3.14.13-stable.3

**Steps to reproduce**
1. Run ima transfers on schain 
2. Check response 

**Actual state**
If  "ChainID transactions" check is enabled on the skaled part any calls to the contracts on schain received empty response 

**Expected behavior**
Calls to skaled should receive valid and full responses 

[skaled_not_allowed_to_call_precompiled_contracts.log](https://github.com/skalenetwork/skaled/files/8879841/skaled_not_allowed_to_call_precompiled_contracts.log)

**Comment by olehnikolaiev** [comment]
couldn't send a call without chainID to skaled due to mandatory chainID check introduced earlier. solution: on processing a call add manually chainID so the check always passes

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Skale Legacy network
schain:3.14.14-stable.6
Estimate gas

```    
request:
curl -X POST -k --data  '{"id":10,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"to": "0xd2AAa00100000000000000000000000000000000","data":"0xc6888fa10000000000000000000000000000000000000000000000000000000000000003"}]}' http://34.208.149.33:10067       
response 
{"id":10,"jsonrpc":"2.0","result":"0x2faf080"}
```


IMA transfers (m2s, s2m):

[ima_test.log](https://github.com/skalenetwork/skaled/files/9102293/ima_test.log)
