### ISSUE TITLE
State root and snapshot support for the archive nodes

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skaled#1173]
Archive nodes need to be able to hold block numbers starting from block 0.

On the other hand archive nodes need to be able to produce state roots and snapshots need to be
compatible with the core nodes.  

This is because one should be able to resurrect the core nodes from the archive nodes.

Therefore, we agreed that the following needs to be done:

1. The current 5 block databases in skaled need to stay as is, without change. The state root calculation needs to stay the same.

2. One needs to introduce database 6. When a database is 5 is rotated, instead of deleting transactions, the blocks, events and other items  need to be moved to database 6.

3. API calls like getBlock need to access database 6 in additiion to database 1,2,3,4,5

FIY https://github.com/skalenetwork/internal-support/blob/main/docs/specifications/skaled/block-rotation.md

**Comment by oleksandrSydorenkoJ** [comment]
Version for testing schain:3.16.0-beta.1-historic

**Comment by oleksandrSydorenkoJ** [comment]
blocked https://github.com/skalenetwork/internal-support/issues/640

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Legacy network 
schain-name: troubled-tall-rotanev/
Versions:skalenetwork/schain:3.16.0-beta.4-historic


root@ip-172-31-60-124:/var/lib/skale/schains/troubled-tall-rotanev/28e07f34/blocks_and_extras# ll
total 0
drwxr-xr-x 1 root root  160 Jan 18 18:07 ./
drwxr-xr-x 1 root root   44 Jan 17 18:48 ../
drwxr-xr-x 1 root root  258 Jan 19 15:13 0.db/
drwxr-xr-x 1 root root 2478 Jan 19 13:24 1.db/
drwxr-xr-x 1 root root 2418 Jan 19 13:24 2.db/
drwxr-xr-x 1 root root 2678 Jan 19 13:24 3.db/
drwxr-xr-x 1 root root 1458 Jan 19 13:24 4.db/
drwxr-xr-x 1 root root   92 Jan 17 19:28 archive-0.db/
drwxr-xr-x 1 root root   92 Jan 18 16:36 archive-1.db/
drwxr-xr-x 1 root root   92 Jan 18 17:35 archive-2.db/
drwxr-xr-x 1 root root   92 Jan 18 17:51 archive-3.db/
drwxr-xr-x 1 root root 2772 Jan 18 18:07 archive-4.db/



eth.getBlock(1).hash
"0x6119a51d5a6445963ca20a5b821586d6490a7715dc93c66498dab8244acf2ccf"
