### ISSUE TITLE
Remove volumes for archive nodes

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skaled#1174]
Arhive nodes need to be able to run without volumes, so the disk space is not limited.

**Comment by badrogger** [comment]
Relates to 
https://github.com/skalenetwork/docker-lvmpy/issues/134
https://github.com/skalenetwork/docker-lvmpy/issues/135

**Comment by badrogger** [comment]
https://github.com/skalenetwork/internal-support/blob/main/docs/specifications/nodes/fullsync-node/archive-node-release.md#versions

**Comment by oleksandrSydorenkoJ** [comment]
Version for testing 
2.2.1-beta-sync-node.1
skalenetwork/admin:2.11.0-beta-sync-node.2

**Comment by oleksandrSydorenkoJ** [comment]
implemented in  https://github.com/skalenetwork/docker-lvmpy/issues/134
