### ISSUE TITLE
Skaled always returns false on the eth_syncing method

### ISSUE THREAD

**Issue by gannakulikova** [skalenetwork/skaled#1199]
**Versions**
Skaled: schain:3.14.15-stable.2

**Environment**
20 active nodes on the network
1 schains up and running 

**Steps to Reproduce/Description**
1. stop skaled container on the node A
2. run small load on blockhain (10 txs per block) for a 1 hour
3. restart skaled container on the node A
4. send eth_syncing call to skaled from the node A during catchup

**Expected behavior**
Skaled should return an json object with currentBlock, highestBlock, strartingBlock values
**Actual result** 
Skaled return false even blockchain is not syncing 

Example request
```
curl <skaled HTTP endpoint > \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":67}'
```

```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/skale-consensus/issues/813
```

**Comment by olehnikolaiev** [comment]
https://github.com/skalenetwork/internal-support/blob/main/docs/specifications/skaled/eth_syncing.md @PolinaKiporenko @DmytroNazarenko lets discuss

**Comment by olehnikolaiev** [comment]
fixed
```
oleh@oleh-ThinkPad-E15:~$ curl -X POST --data '{"method":"eth_blockNumber","params":["stringValueInsteadOfBlockNuber"],"id":1,"jsonrpc":"2.0"}' http://localhost:1234
{"error":{"code":-32602,"data":null,"message":"INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised"},"id":1,"jsonrpc":"2.0"}oleh@oleh-ThinkPad-E15:~$ 
oleh@oleh-ThinkPad-E15:~$ 
oleh@oleh-ThinkPad-E15:~$ 
oleh@oleh-ThinkPad-E15:~$ curl -X POST --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}' http://localhost:1234
{"id":1,"jsonrpc":"2.0","result":"0x3f"}
```

**Comment by DmytroNazarenko** [comment]
skaled: 3.18.0-beta.0

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network
skaled: 3.18.0-beta.0
Skale chain: aged-wry-finished-skale

**Skaled is catching up**:
JSON-RPC call 
```
curl  --data '{"id":4,"jsonrpc":"2.0","method":"eth_syncing","params":[]}' http://100.21.164.124:10195

{"id":4,"jsonrpc":"2.0","result":{"currentBlock":37047,"highestBlock":37058,"startingBlock":36750}}
```

Geth:
```
> eth.syncing
{
  currentBlock: 37003,
  highestBlock: 37058,
  startingBlock: 36750
}
```

**After syncing with majority of nodes:**
```
{"id":4,"jsonrpc":"2.0","result":false}

> eth.syncing
false

```
