### ISSUE TITLE
eth_getBalance() fails on historic state

### ISSUE THREAD

**Issue by dimalit** [skalenetwork/skaled#1208]
```{"id":32,"jsonrpc":"2.0","method":"eth_getBalance","params":["0xa68F946090c600eDa6f139783077EE802Afeb990","latest"]}```
Client::alethStateBalanceAt() throws exception in AlethState::setRootByBlockNumber(uint64_t _blockNumber)
(_blockNumber = 4294967294)

**Comment by oleksandrSydorenkoJ** [comment]
Still actual for skalenetwork/schain:3.14.15-sync.12-historic

**Comment by kladkogex** [comment]
Hey guys

I am closing this bug because there is no function Client::alethStateBalanceAt

Looks like you are using a very old build

**Comment by kladkogex** [comment]
Fixed )

**Comment by oleksandrSydorenkoJ** [comment]
Version for test skalenetwork/schain:3.16.0-beta.1-historic

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Legacy network
schain name: troubled-tall-rotanev


 skalenetwork/schain:3.16.0-beta.1-historic


```
> eth.getBalance('0xb04a7f2cd74eb624df4bd8bed8f7034b5aed89c0', 120)
1e+30
> eth.getBalance('0xb04a7f2cd74eb624df4bd8bed8f7034b5aed89c0', 150)
9.998999999999999999979000001e+29
> eth.getBalance('0xb04a7f2cd74eb624df4bd8bed8f7034b5aed89c0', 1900)
9.998999999999999009009000001e+29
> eth.getBalance('0xb04a7f2cd74eb624df4bd8bed8f7034b5aed89c0', 72900)
9.998999999844082038817350001e+29
> eth.getBalance('0xb04a7f2cd74eb624df4bd8bed8f7034b5aed89c0', 168505)
9.998999999844082026971302001e+29
> eth.getBalance('0xb04a7f2cd74eb624df4bd8bed8f7034b5aed89c0', "latest")
9.998999999844082026846209001e+29
```
