### ISSUE TITLE
change `v` value output format in txn signature

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/skaled#1210]
Specification from https://eips.ethereum.org/EIPS/eip-155
If block.number >= FORK_BLKNUM and CHAIN_ID is available, then when computing the hash of a transaction for the purposes of signing, instead of hashing only six rlp encoded elements (nonce, gasprice, startgas, to, value, data), you SHOULD hash nine rlp encoded elements (nonce, gasprice, startgas, to, value, data, chainid, 0, 0). If you do, then the v of the signature MUST be set to {0,1} + CHAIN_ID * 2 + 35 where {0,1} is the parity of the y value of the curve point for which r is the x-value in the secp256k1 signing process. If you choose to only hash 6 values, then v continues to be set to {0,1} + 27 as previously.

skaled output `v` value as {0,1}, that should be changed in order to be fully compatible with geth and so users can verify txns signatures using standard tools

**Comment by gannakulikova** [comment]
@kladkogex @cstrangedk  guys please review

**Comment by gannakulikova** [comment]
Assigning to 2.2 release per @kladkogex @cstrangedk  feedback

**Comment by oleksandrSydorenkoJ** [comment]
Version for testing:
schain:3.16.0-beta.4  - for core and sync-nodes
schain:3.16.0-beta.4-historic - for archive node

there are 2 options to calculate the "v" value:
1. transaction with chainID
2. transaction without chainID

Steps to reproduce 
The transaction with chainID:
1. Calculate v value 
`` {0,1} + CHAIN_ID * 2 + 35``
example, chainID is 0x000001654f244 = 374665796
v value = {0,1} + 374665796*2 + 35 = 749331627 or 749331628
2. send a transaction to schain with chainID ``0x000001654f244``
3. Check Block by number with true parameter
``    curl -X POST -k --data  '{"id":29,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":[<block with trnsactions>,true]}' HTTP-endpoint``       
4. check v value in response = should be equal for one of 2 results from step 1


The transaction withou chainID:
1. send a transaction to schain without chainID
2.  Check Block by number with true parameter
``    curl -X POST -k --data  '{"id":29,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":[<block with trnsactions>,true]}' HTTP-endpoint``     
3.  check v value in response = should be 27 or 28

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Legacy network
schain name: troubled-tall-rotanev
chainId: 0x000001654f244
archive node endpoint: ``http://52.42.213.142:10323``

Check with chainID
1. v value = {0,1} + 374665796*2 + 35 = 749331627 or 749331628
2. transaction 0x8dddd87bd773bfa76c074e95f1e193d43abd8d9cd9f4741bca39204e482e7b5c
https://troubled-tall-rotanev.legacy-explorer.skalenodes.com/tx/0x8dddd87bd773bfa76c074e95f1e193d43abd8d9cd9f4741bca39204e482e7b5c/logs
3. eth.getBlock(7700, true)
 v: "0x2ca9e4ac", = 749331628

Check without Chain ID
1. Transaction without chainID 0x08286b597cdf22e5ad194dacc778d3e2afb7cad5ec418206eed7112badffbeb6
https://troubled-tall-rotanev.legacy-explorer.skalenodes.com/tx/0x08286b597cdf22e5ad194dacc778d3e2afb7cad5ec418206eed7112badffbeb6/internal-transactions
2. eth.getBlock(262106, true)
    v: "0x1c"


for another transaction without chainID:
1. 0xcb7bb93aea513a7ae6af4ec6c6d71fcaac0eab39c1c3b624354e7b94bd3d252d
2.   eth.getBlock(262110, true)
3.   v: "0x1b",

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network
schain: wan-tasty-kitalpha

Version: skalenetwork/schain:3.16.0-beta.6


http://wan-tasty-kitalpha.regression-explorer.skalenodes.com/block/711/transactions

1. Chain ID = 0x00000152e7be9  = 355367913
355367913*2+35 = 710735861 = 0x2a5cf7f5 

2. eth.getBlock(711, true)
`` v: "0x2a5cf7f5",``
