### ISSUE TITLE
block gas limit is not respected in proposal

### ISSUE THREAD

**Issue by dimalit** [skalenetwork/skaled#1211]
All available transactions from TQ go to block proposal.
Need to limit this only to those, which fit under block gas limit.

see SkaleHost::pendingTransactions()

**Comment by gannakulikova** [comment]
assigning to 2.2 release per @cstrangedk  feeback

**Comment by gannakulikova** [comment]
per @kladkogex , assigning to 2.1

**Comment by DmytroNazarenko** [comment]
skaled:3.16.0-beta.6

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network
schain: wan-tasty-kitalpha
Version: skaled:3.16.0-beta.6

Steps to reproduce:
1. Send 4 transactions with gasLimit 100,000,000
2. Check blocks where transactions were mined

Result:
2 transactions are in block, and other transactions in staying in the transaction queue and will be inserted to the next block 
http://wan-tasty-kitalpha.regression-explorer.skalenodes.com/block/20873/transactions
http://wan-tasty-kitalpha.regression-explorer.skalenodes.com/block/20874/transactions
