### ISSUE TITLE
skaled RAM usage grows infinitely

### ISSUE THREAD

**Issue by dimalit** [skalenetwork/skaled#1223]
RSS grew and didn't stop growing on every node of 16-node chain (no transaction load).
After Stan added free() to some EDDSA-related code, problem gone:https://github.com/skalenetwork/skale-consensus/pull/707/files

**Comment by dimalit** [comment]
GROW commit a124049f109783026fd9743a98eb30ae1b5b4d93 (HEAD -> develop, tag: 3.15.13-develop.7, origin/develop, origin/HEAD)
commit 3d0145f4829b8996b14235e9c9708a653dabc2a0 (tag: 3.15.13-develop.6)
commit 295f5c254b326564755f9b715b569f3eb1e08f84 (tag: 3.15.13-develop.5)
commit a15e7d2158a3f6aa80450f4904f5dddaff025727 (tag: 3.15.13-develop.4)
commit c82018afa9f37a0b0ca15caaab764ced9e98216d (tag: 3.15.13-develop.3)
commit 336600e1901e1af0c5f4606e799e9e99ce7ef577 (tag: 3.15.13-develop.2)
commit 0ac4782a4472364b671bf3ef6d5b15688848b433 (tag: 3.15.13-develop.1)
commit fb237e6b24b9f9fa306169c327c0061c6ef21d7a (tag: 3.15.13-develop.0)
commit 350f3caeaaeac31f28fa673a0dabe388bf5b5828 (tag: 3.15.12-develop.0)
commit 8b98d5f4b0cd22967e062280a07469ecb1c73717 (tag: 3.15.11-develop.2)
commit 0862cb2897b2a24526291b9c17dedd0cb6991ce2 (tag: 3.15.11-develop.1)
commit 8bfa6bb4c5e9fb89442d4176abae4d3706b24bb5 (tag: 3.15.11-develop.0)
commit 65a0b9425cc9f28d08e5657822c45eced53630c5 (tag: 3.15.10-develop.1)
GROW commit d40dee9f8c0c608657ec2134d49cc1d8a2abd029 (tag: 3.15.10-develop.0)
GROW commit 76472258218cc707e5a27c7a5f189d7c0f6a4216 (tag: 3.15.9-develop.8) (0->1G->0->250M)
commit b5ee23207e18544834b364c5126ee024d35e1e81 (tag: 3.15.9-develop.7)
GROW? commit d8ab0ec802fda7989c1c1e3ed3b23dee931fd27f (tag: 3.15.9-develop.6) (tested till 250M)
commit ef2736b0750722bdb808fbc375c5e525310761f8 (tag: 3.15.9-develop.5)
GROW commit 073b0b19e9b5e8995ebf56ebbaab24427bf755e5 (tag: 3.15.9-develop.4)
commit ac6b6d22c5cb0ec766865c0880be7e05373e2f6a (tag: 3.15.9-develop.3)
GROW commit 7f8eb5365d91ef0aa47ef0d03e69456b1690d14e (tag: 3.15.9-develop.2)
GROW commit 6b9dc4b2ea5777d4be56b05c9b88dbc41059c8b2 (tag: 3.15.9-develop.1)
-NO GROW commit 61ca3397cc9c7193173ecb3e92fc642cd1a492e6 (tag: 3.15.9-develop.0)
+GROW commit a0ae820dbadd458d421b01ceab6776785535c29f (tag: 3.14.15-beta.0, origin/beta, beta)
commit f55e08f464c1dc944bee0a3aa80d7fc860743da1 (tag: 3.15.8-develop.2)
GROW commit cca7561e3211e2c0e9367e9ddc1204ab0b0297a5 (tag: 3.15.8-develop.1)
GROW commit e783990b2190dd3e30e2c85c0fe87b67393aa95c (tag: 3.15.8-develop.0)

SIGSEGV 3.15.4-develop.2
SIGSEGV 3.15.4-develop.1
NO GROW 3.15.4-develop.0


*NO GROW 3.14.15-stable.2
+NO GROW commit d2db9596a9df50c5e399fcca37e22c9d05599ab1 (tag: 3.14.15-stable.1)

**Comment by dimalit** [comment]
Looks like, problem was introduced here https://github.com/skalenetwork/skaled/compare/3.15.9-develop.0...3.15.9-develop.1
And probably, that was this commit https://github.com/skalenetwork/skaled/commit/6f623e688bf105d32ad39d1ee3221fbe5a6e47d1

PS Look like it was false assumption, see below

**Comment by gannakulikova** [comment]
assigning to 2.1 per @kladkogex 's feedback

**Comment by dimalit** [comment]
Caught (first) signal. Signal SIGSEGV(11). When an application has a segmentation violation, this signal is sent to the process.


[2022-12-05 19:13:21.095] [15:main] [debug] 0:NtwkRdLoop zmq debug: receiveSocket = 140340874990672
[2022-12-05 19:13:21.096] [15:main] [debug] 0:Successfull bound ZMQ socket
  /skaled/skaled : ()+0x94ec36
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x12980
  /skaled/skaled : CryptoManager::getECDSAHistoricPublicKeyForNodeId[abi:cxx11](unsigned long, unsigned long)+0x27
  /skaled/skaled : CryptoManager::getECDSAPublicKeyForNodeId[abi:cxx11](node_id const&, unsigned long)+0x174
  /skaled/skaled : CryptoManager::verifyECDSASig(BLAKE3Hash&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, node_id)+0x9a
  /skaled/skaled : CryptoManager::verifyProposalECDSA(std::shared_ptr<BlockProposal> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1eb
  /skaled/skaled : BlockProposal::deserialize(std::shared_ptr<std::vector<unsigned char, std::allocator<unsigned char> > > const&, std::shared_ptr<CryptoManager> const&)+0x32f
  /skaled/skaled : BlockProposalDB::getBlockProposal(block_id, schain_index)+0x4fb
  /skaled/skaled : Schain::proposeNextBlock()+0x26a
  /skaled/skaled : Schain::bootstrap(block_id, unsigned long, unsigned long)+0x9a0
  /skaled/skaled : ConsensusEngine::bootStrapAll()+0x35d
  /skaled/skaled : ()+0xa997ae
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6 : ()+0xd44c0
  /lib/x86_64-linux-gnu/libpthread.so.0 : ()+0x76db
  /lib/x86_64-linux-gnu/libc.so.6 : clone()+0x3f

**Comment by dimalit** [comment]
![image](https://user-images.githubusercontent.com/6162220/205725161-c4f99121-a100-46d1-9c51-fdf7779148de.png)

**Comment by dimalit** [comment]
Problem appeared in this range:
https://github.com/skalenetwork/skaled/compare/3.15.4-develop.0...3.15.4-develop.3

3.15.4-develop.0 + consensus from develop.3 - SGX = NO GROW
3.15.4-develop.3 - SGX = NO GROW
=> SGX is needed for grow

Finally
3.15.4-develop.0 + SGX = NO GROW
3.15.4-develop.0 + consensus from develop.3 + SGX = GROW

**Comment by gannakulikova** [comment]
Fixed by https://github.com/skalenetwork/skale-consensus/issues/706 per @kladkogex  (cc @DmytroNazarenko )
moving for QA verification in scope of 2.1 release

**Comment by DmytroNazarenko** [comment]
skaled:3.16.0-beta.6

**Comment by oleksandrSydorenkoJ** [comment]
Actual for skalenetwork/schain:3.16.0-beta.6
RAM doesn't clear over time even no any load on schain

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network
skalenetwork/schain:3.16.0-beta.6

RAM grows up to 90% and doesn't change over time. 

There are separate issues that will be fixed in https://github.com/skalenetwork/skaled/issues/635 (core nodes) and  https://github.com/skalenetwork/skaled/issues/1355 (archive nodes )

**Comment by EvgeniyZZ** [comment]
Update description details, result

**Comment by oleksandrSydorenkoJ** [comment]
[T12193](https://skaleqa.testrail.io/index.php?/tests/view/12193)

**Comment by EvgeniyZZ** [comment]
Mark as resolved
