### ISSUE TITLE
Implement eth_call cache 

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skaled#1239]
If the block number does not change, the result of the eth_call does not change

For multiple identical eth_call requests this means that we can implement a cache of results.

**Comment by gannakulikova** [comment]
assigning to Archive node release per discussion with @kladkogex @DmytroNazarenko

**Comment by DmytroNazarenko** [comment]
Related to https://github.com/skalenetwork/internal-support/issues/548
