### ISSUE TITLE
Need to provide ddos protection for all IPs

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1241]
Currently our DDOS protection handles and limits calls from one IP. We need to have an ability to handle overall number of calls from all IPs. Will help us to have readable errors and strict limits for calls. 

Need to add this to "unddos" section of skaled config

**Comment by DmytroNazarenko** [comment]
Related to https://github.com/skalenetwork/internal-support/issues/548

**Comment by gannakulikova** [comment]
Assigned to 2.1 release

**Comment by DmytroNazarenko** [comment]
Not working on syncnode 3.14.15-sync.11

**Comment by DmytroNazarenko** [comment]
Max calls per second = 300-400 on syncnode 3.14.15-sync.17. Need to be fixed

**Comment by DmytroNazarenko** [comment]
skaled:3.16.0-beta.6

**Comment by oleksandrSydorenkoJ** [comment]
Version: skaled:3.16.0-beta.6



Origins:
max_calls_per_second: 10 - failed after 17 requests from 1 Ip
```
Error: Returned error: {"error":"Banned due to high load JSON RPC request: {\"id\":17,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBlockByNumber\",\"params\":[\"0xf\",true]}","id":17}
```

max_calls_per_second: 1000 - failed after 2175 request from 1 IP
```
Error: Returned error: {"error":"Banned due to high load JSON RPC request: {\"id\":2175,\"jsonrpc\":\"2.0\",\"method\":\"eth_getBlockByNumber\",\"params\":[\"0x87d\",true]}","id":2175}
```

other IP:
load cat-cycle tests (100 users per 10 txs from single user)


![Image](https://user-images.githubusercontent.com/84327300/215079516-743f7dd4-3378-40ea-bea5-41c4b1c662a9.png)
