### ISSUE TITLE
Merge syncnode branch to develop

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1250]
Merge syncnode branch to develop and move to stage 2, according to this doc:
https://github.com/skalenetwork/internal-support/blob/main/docs/specifications/nodes/fullsync-node/branching-strategy.md#stage-ii

Steps: 
1. Fix stable-develop branching (https://github.com/skalenetwork/skaled/issues/1227)
2. Review and merge PR (https://github.com/skalenetwork/skaled/pull/1249)

**Comment by gannakulikova** [comment]
assigned to 2.1 per @kladkogex  for now

**Comment by EvgeniyZZ** [comment]
Not for QA
