### ISSUE TITLE
All state's leveldb files changes on the volume during destructing data on the contract 

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1268]
**Versions**
Skaled: skalenetwork/schain:3.14.15-stable.2

**Environment**
20 active nodes on the network
6 schains up and running 

**Preconditions**
Contract storage occupied for a 3 GB
enabled qouta 
```btrfs quota enable /mnt/schain-name```

**Steps to Reproduce/Description**
1. Check btrfs qgroups on the chain and save output
```
 btrfs qgroup show  /mnt/schains-schain_name
```
2.  Save the time of changes levelDB files in the schain mounted directory
```
ls -la /mnt/schains-composed-bouncy-kaffaljidhma/28e07f34/12041/state
```

3. Run contract call to destrcut data from contract-storage
4. Check btrfs qgroups on the chain and the time of changes levelDB files in the schain mounted directory again

**Expected behavior**
After self-destructing, should be changed delta that equals to removed data from contract storage 
Shoudl be changed LevelDB files that included data of changes on the  contracts

**Actual result** 
Removed from the contract on schain is 1545216 bytes
All levelDB files in the contract storage are replaced and has new date
BTRFS exclusive files for contract storage are 3.55 GB

[btrfs_snapshots.log](https://github.com/skalenetwork/internal-support/files/10177457/btrfs_snapshots.log)
[btrfs_delta_after_test.log](https://github.com/skalenetwork/internal-support/files/10177458/btrfs_delta_after_test.log)
[btrfs_delta_before_test.log](https://github.com/skalenetwork/internal-support/files/10177459/btrfs_delta_before_test.log)
[levelDB_changes.log](https://github.com/skalenetwork/internal-support/files/10177460/levelDB_changes.log)

**Comment by DmytroNazarenko** [comment]
related to https://github.com/skalenetwork/internal-support/issues/306

**Comment by oleksandrSydorenkoJ** [comment]
Fixed by new version of LevelDB https://github.com/skalenetwork/skaled/pull/1519
