### ISSUE TITLE
Historic state works incorrectly for zero block

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skaled#1271]
Historic state works incorrectly for zero block due to incorrectly written database keys

**Comment by PolinaKiporenko** [comment]
@kladkogex will provide more detailed description of the issue

**Comment by kladkogex** [comment]
Block 0 is the genesis block.  It includes predeployed contracts and can also includes starting amount of ETH for different accounts.

The bug was that you could not specify the block number "0" in eth_getBalance. Now you can do it

**Comment by kladkogex** [comment]
@PolinaKiporenko @oleksandrSydorenkoJ
