### ISSUE TITLE
findMostRecentBlocksDBPath fails on fresh data_dir

### ISSUE THREAD

**Issue by dimalit** [skalenetwork/skaled#1297]
1. Run skaled with enabled snapshots on empty data_dir
2. `2022-12-30 12:56:38.024025   DB path is: btrfs/1
2022-12-30 12:56:38.024265   CRITICAL Could not find BlocksDB at btrfs/1/blocks_1.db.The provided path does not exist. ---`

Related to https://github.com/skalenetwork/skaled/issues/1270

**Comment by dimalit** [comment]
See branch SKALED-1250-sync-to-develo_p

**Comment by dimalit** [comment]
Decided to comment this out, fix later

**Comment by kladkogex** [comment]
Closing this since the new implementation does not use this function
