### ISSUE TITLE
Create build/test pipeline for historic state

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1306]
*Technical debt*

Need to create the same pipeline to build and test skaled with historic state as we have for regular version of skaled:
- For pull requests there should be separate job for historical state (or part test.yml)
- Job should build skaled with historic state and run tests on it (historic + non-historic tests)

**Comment by DmytroNazarenko** [comment]
Build is added. Tests should be added

**Comment by EvgeniyZZ** [comment]
Not reqire QA afford
