### ISSUE TITLE
Skaled and consensus not stoped gracefully

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1348]
Details:
- [x] https://github.com/skalenetwork/internal-support/issues/554

**Comment by dimalit** [comment]
Research shows, that skaled has problems with exit mostly when there is "exit time reached". so need to address this first
https://github.com/skalenetwork/skaled/issues/1415

**Comment by dimalit** [comment]
See also https://github.com/skalenetwork/skaled/issues/1503

**Comment by DmytroNazarenko** [comment]
blocked by https://github.com/skalenetwork/skaled/issues/1415 per @dimalit

**Comment by dimalit** [comment]
TO QA: Re-test this issue after SKALED-1425 merge

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.1

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network
Version: 3.17.0-beta.8

2 bugs related to this issue will be fixed separately 
https://github.com/skalenetwork/skaled/issues/1425 
https://github.com/skalenetwork/skale-admin/issues/976 

Other checks with all graceful expected exits- passed
expected exits after:
Node rotation, state root error, SSL update, node update, and consensus restart after timeout without new blocks
 


[threading_rules_skaled_consensus.txt](https://github.com/skalenetwork/skaled/files/12619881/threading_rules_skaled_consensus.txt)
