### ISSUE TITLE
Skaled returns invalid value for blocks_and_extrass db usage on skale_getDbUsage call

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1350]
**Versions**
Skaled: 3.14.16-beta.4

**Environment**
20 active nodes on the network
1 active schain with connected archive node 

**Preconditions**
1 database rotation on schain
Connected archive node 

**Steps to Reproduce/Description**
1. run low load on schain
2. check blocks_and_extrass db usage for archive node
``curl -X POST --data '{ "jsonrpc": "2.0", "method": "skale_getDBUsage", "params": { }, "id": 73 }' http-endpoint"
3. check blocks_and_extrass database usage on the node 
 ``du -sh /var/lib/skale/schains/schain-name/28e07f34/``

**Expected behavior**
skaled should return actual database usage for every database on schain

**Actual result** 
Skaled returns 996398796 bytes instead of 505

rapid-json
``` 
curl -X POST --data '{ "jsonrpc": "2.0", "method": "skale_getDBUsage", "params": { }, "id": 73 }' http://44.233.84.119:10323

{"id":73,"jsonrpc":"2.0","result":{"consensusDBUsage":{"block_proposal.db_disk_usage":134708662,"block_sigshare.db_disk_usage":413,"blocks.db_disk_usage":435054743,"consensus_state.db_disk_usage":413,"da_proof.db_disk_usage":9088217,"da_sigshare.db_disk_usage":6426298,"incoming_msg.db_disk_usage":413,"interna_info.db_disk_usage":661,"outgoing_msg.db_disk_usage":1619528,"price.db_disk_usage":5039475,"proposal_hash.db_disk_usage":11658353,"proposal_vector.db_disk_usage":7493351,"random.db_disk_usage":413},"skaledDBUsage":{"blocks.db_disk_usage":996398796,"contractStorageUsed":72480,"pieceUsageBytes":4034519,"state.db_disk_usage":15925009}}}
```

internal check via du 
```
du -sh /var/lib/skale/schains/troubled-tall-rotanev/28e07f34/*
493M	/var/lib/skale/schains/troubled-tall-rotanev/28e07f34/blocks_and_extras

```

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network
Version: skalenetwork/schain:3.16.0-beta.9
Skale chain name: chubby-alderamin

``curl -X POST --data '{ "jsonrpc": "2.0", "method": "skale_getDBUsage", "params": { }, "id": 73 }' http://100.21.94.22:10451``

```
skaledDBUsage":{"blocks.db_disk_usage":1262203826,"contractStorageUsed":23264,"pieceUsageBytes":196676472,"state.db_disk_usage":2748454}}}
```

On node:
```
:/mnt/schains-chubby-alderamin/28e07f34# du -s *
2704	12041
1234000	blocks_and_extras

root@ip-172-31-48-166:/mnt/schains-chubby-alderamin/28e07f34/blocks_and_extras# du -s *
193920	3.db

```
