### ISSUE TITLE
Shared space not cleared before downloading new snapshot

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1433]
**Version:**
schain:3.16.0-stable.1

**Preconditions:**
Active schain
20 nodes
Tools for decrease network speed
Snapshot interval - 1 hour

**To Reproduce**
1. Decrease network performance to 1500 Kb upload/ 3500 Kb Download on node A
2. Restart any skaled from the node A from the snapshot - skaled on node shouldn't download more than 1 snapshot fragment
3. Wait for 3 snapshot intervals
4. Check shared-space datadir

**Expected behavior**
Shared-space should be cleaned before every snapshot downloading procedure
 
**Actual state**
If 1 skaled occupied shared space, snapshot fragments won't be removed from shared space until new skaled will occupies the shared space directory

**Note:**
After switch back to the base network performance the error is disappeared.  
If the skaled successfully downloaded the snapshot - the next skaled will clean up the shared space. 

```
$ /mnt/schains-shared-space/data# ls -la
total 819216
drwxr-xr-x 1 root root       118 Feb 22 15:26 .
drwxr-xr-x 1 root root         8 Feb 21 18:58 ..
-rw-r--r-- 1 root root         0 Feb 22 15:26 .lock
-rw-r--r-- 1 root root 104857600 Feb 22 00:03 195506
-rw-r--r-- 1 root root 104857600 Feb 22 01:59 196092
-rw-r--r-- 1 root root 104857600 Feb 22 05:03 196969
-rw-r--r-- 1 root root 104857600 Feb 22 07:04 197559
-rw-r--r-- 1 root root 104857600 Feb 22 09:04 198149
-rw-r--r-- 1 root root 104857600 Feb 22 11:03 198739
-rw-r--r-- 1 root root 104857600 Feb 22 13:02 199328
-rw-r--r-- 1 root root 104857600 Feb 22 15:01 199920
-rw-r--r-- 1 root root         0 Feb 22 15:26 200509
```

**Comment by olehnikolaiev** [comment]
the space occupied by shared space does not affect skaled storage and its performance. other than that, shared space will be cleaned up by the next skaled which will be downloading snapshot. suggest to close. cc @oleksandrSydorenkoJ

**Comment by DmytroNazarenko** [comment]
skaled: 3.18.0-beta.0
