### ISSUE TITLE
Be able to catchup from 0 block

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1450]
**What?**
We need to catchup 0 block in the process of catchup. Currently we run catchup from 1st block and for 0 block we are using genesis from config

**Why?**
To be able to catchup genesis block from another node and do not be dependent from predeployeds in the config. These can help us to avoid STATE_ROOT because of different genesis block

**Who?**
This feature will help engineering team and archive node maintainers. It will help to simplify maintaining and deployment process of the archive node

**Comment by olehnikolaiev** [comment]
https://github.com/skalenetwork/internal-support/blob/main/docs/issues-and-investigations/catchup-from-0-block.md

**Comment by DmytroNazarenko** [comment]
For v2.1 and previous chains (for those who are already on mainnet chains before 2.2 release):
- Precalculate genesis blocks (1st group and predeployeds)
- Store precalculated genesis in skale-admin

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.1
skale-node: beta-sync-node

**Comment by oleksandrSydorenkoJ** [comment]
Closed as implemented in
https://github.com/skalenetwork/skale-admin/issues/944
https://github.com/skalenetwork/skaled/issues/1612
