### ISSUE TITLE
Update CI to support new Ubuntu version

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1456]
* PRD: SYSTEM UPGRADE
* **Warning**: Github Actions will drop Ubuntu 18.04 runner on April 1st (https://github.com/actions/runner-images/issues/6002), which will affect both development and testing.

Skaled container should be being built on Ubuntu 20.04. CI process should be adjusted to use Ubuntu 20.04 version (both container build and unit tests)

**Comment by dimalit** [comment]
blocked by https://github.com/skalenetwork/skaled/issues/1465

**Comment by EvgeniyZZ** [comment]
Not required QA afford
