### ISSUE TITLE
Fix stucks in oracle requests

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1458]
Description:
* https://github.com/skalenetwork/internal-support/issues/40

**Comment by kladkogex** [comment]
Will be testing tomorrow.

Oracle now has a separate queue compared to consensus, but problems can still happen.

**Comment by DmytroNazarenko** [comment]
Need to be retested on 3.16.1-beta.1

**Comment by oleksandrSydorenkoJ** [comment]
Moved to review
