### ISSUE TITLE
Add historic_roots and historic_state directories to snapshot for the archival node

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1474]
To start the archival node from the snapshot from a custom peer, need to add to the snapshot 2 directories historic_roots and historic_state
Need to be sure, that the archival node does support the historical state before downloading the snapshot.

Related to https://github.com/skalenetwork/skaled/issues/1144

**Comment by oleksandrSydorenkoJ** [comment]
Consensus databases on the archival node are rotated as on core nodes and after 4th rotation skaled invoke blocks prune for the 1st database. 
To avoid losing data and the ability to start the archival node, need to add historic_roots and historic_state directories to the snapshot
