### ISSUE TITLE
Integrate functional tests into CI

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1484]
For better code quality we need to provide an additional round of testing after skaled build will be created
* We need to integrate skale-ci-integration_tests into publish pipeline for published skaled containers
* Add PR checks for develop and beta branches for passing these tests

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.1

**Comment by EvgeniyZZ** [comment]
Not required QA
