### ISSUE TITLE
Clean warnings in skaled build

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skaled#1508]
**Describe the bug**

Currently skaled build has lots of warnings

Some of them come from libbls (Oleh has a separate bug for it). There are also two warnings in consensus - Stan will address them 

As part of code quality OKRs,  release 2.2 has no warnings

**To Reproduce**

Build skaled

**Expected behavior**
Skaled build should have no warnings

Please disable warning either:

- using cmake flags
- or, if you want to disable them in a single file please use 

push pragma as described here 

https://www.fluentcpp.com/2019/08/30/how-to-disable-a-warning-in-cpp/#:~:text=To%20disable%20a%20set%20of,pop%E2%80%9D%20pre%2Dprocessor%20instruction.

**Comment by oleksandrSydorenkoJ** [comment]
Not for QA

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.1
