### ISSUE TITLE
Remove un-needed skaled parts for release 2.2.

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/skaled#1511]
With release 2.2 IMA becomes mostly self-containing and following parts of `skaled` became parts of `IMA Agent`:
- `skale_imaVerifyAndSign`, `skale_imaBSU256` JSON RPC API
- `SKALE Network Browser` APIs
These parts are no longer needed in `skaled` and must be excluded from source code.

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.1

**Comment by EvgeniyZZ** [comment]
Verified:
Skale: 3.17.0-beta.7
Request:
``curl -X POST --data '{"jsonrpc":"2.0","method":"skale_browseEntireNetwork","params":[],"id":1}' http://12.345.578.90:12345 -H "Content-type: application/json"``
Response:
``{"error":{"code":-32601,"message":"METHOD_NOT_FOUND: The method being requested is not available on this server"},"id":1,"jsonrpc":"2.0"}``
Request:
``
curl -X POST --data '{"jsonrpc":"2.0","method":"skale_cachedEntireNetwork","params":[],"id":1}' http://12.345.578.90:12345  -H "Content-type: application/json"
``
Response:
``{"error":{"code":-32601,"message":"METHOD_NOT_FOUND: The method being requested is not available on this server"},"id":1,"jsonrpc":"2.0"}``
Request: 
``curl -X POST --data '{ "jsonrpc":"2.0","id":627323538317512,"method": "skale_imaVerifyAndSign", "params": { "direction": "S2S", "startMessageIdx": "12", "dstChainName": "portly-passionate-sirius", "srcChainName": "curly-red-alterf", "dstChainID":" 1000", "srcChainID": "0x000001fe6cdfa", "messages": [{ "sender": "0xD2aaA00900000000000000000000000000000000", "destinationContract": "0xD2aaA00900000000000000000000000000000000", "data": "0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000b00000000000000000000000041339d410233218185932b8036a661218b2d85db0000000000000000000000007aa5e36aa15e93d10f4f26357c30f052dacdde5f00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000003e700000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000003e9", "savedBlockNumberForOptimizations": "343"}], "qa": { "skaledNumber": "0", "optsSignOperation.sequenceId": "25b0088723ce10ebb3d6c352201a1da79a662f2502d09313e17e71bbb9fde79f", "ts": "2023-08-15 11:36:26.389"}}}' http://12.345.578.90:12345 -H "Content-Type: application/json"``

Response:
``{"error":{"code":-32601,"message":"METHOD_NOT_FOUND: The method being requested is not available on this server"},"id":627323538317512,"jsonrpc":"2.0"}``
Request:
``curl -X POST --data '{"jsonrpc":"2.0","method":"skale_imaBSU256","params":[],"id":1}' http://12.345.578.90:12345  -H "Content-type: application/json"``
Response: 
``{"error":{"code":-32601,"message":"METHOD_NOT_FOUND: The method being requested is not available on this server"},"id":1,"jsonrpc":"2.0"}``
