### ISSUE TITLE
snapshot hash calculation should be aborted on exit

### ISSUE THREAD

**Issue by dimalit** [skalenetwork/skaled#1525]
When skaled receives SIGTERM or is going to exit in some other way, it should not wait for snapshot hash calculation to finish (as it can take too long). Instead, it should abort snapshot hash calculation, and at next start - if hash is not present - skaled should calculate it from scratch.

**Comment by oleksandrSydorenkoJ** [comment]
Actual for skalenetwork/schain:3.17.0-beta.6

during catching-up skaled calculates snapshot hash (state size near 2-3 GB, so it takes a while)
after receiving the sigterm signal Skaled finished the process but doesn't abort snapshot hash calculation

How to test:
1. Run state loader test up to 2 GB
2. Stop skaled container on node A 
3. Run state loader test for a 3 GB
4. Restart skaled node A and check skaled container 
5. Run Docker stop with timeout 300 seconds 


Skaled should stop calculating the snapshot hash after receiving the Sigterm signal 

[snapshot_hash_calculation_on_abort.txt](https://github.com/skalenetwork/skaled/files/12241933/snapshot_hash_calculation_on_abort.txt)

**Comment by dimalit** [comment]
Snapshot hash calculation is successfully aborted after 270 sec timeout.

[aleth.out.txt](https://github.com/skalenetwork/skaled/files/12321724/aleth.out.txt)
[aleth.err.txt](https://github.com/skalenetwork/skaled/files/12321725/aleth.err.txt)

**Comment by oleksandrSydorenkoJ** [comment]
Cannot reproduce on the chain with 7GB state with 10kb/second disk Read\Write speed

Snapshot hash calculation time is ~ 2 minutes and timeout doesn't excited 300 seconds  

[skaled_stops_durig_stucs_after_300_seconds_downtime.log](https://github.com/skalenetwork/skaled/files/12361669/skaled_stops_durig_stucs_after_300_seconds_downtime.log)

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0

**Comment by oleksandrSydorenkoJ** [comment]
Verified on the Legacy network 

skaled: 3.17.1
1. Stop skaled during calculation snapshot hash
2. restart skaled from the catchup and check skaled starts to calculate the snapshot hash
 
[Abort_on_snapshot_hash_calculation_3_17_1.txt](https://github.com/skalenetwork/skaled/files/13381018/Abort_on_snapshot_hash_calculation_3_17_1.txt)
