### ISSUE TITLE
Net_version incorrect format of result

### ISSUE THREAD

**Issue by payvint** [skalenetwork/skaled#1526]
There is a JSON RPC call `net_version` which is returning chain id.
Currently it is returning a correct number but in incorrect base - hex, it should return number as a decimal.

Ref to doc: https://ethereum.org/en/developers/docs/apis/json-rpc/#net_version

**Comment by DmytroNazarenko** [comment]
3.17.2-develop.2

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Legacy network 

skalenetwork/schain:3.18.0
skalenetwork/schain:3.18.1-develop.0-historic
```
 curl -X POST --data '{"jsonrpc":"2.0","method":"net_version","params":[],"id":67}' http://localhost:10131
{"id":67,"jsonrpc":"2.0","result":"3547699397854811"}
```
