### ISSUE TITLE
Incorrect value in logs for CPU usage

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1527]
@badrogger @kladkogex to add description
CPU is always `-1` according to the logs

**Comment by badrogger** [comment]
Example:
`Block stats:BN:2736000:BTS:1687348519:TXS:0:HDRS:11:LOGS:94:SENGS:1:TXRS:706:BLCKS:3:ACCS:101:BQS:1:BDS:10044:TSS:0:UTX:0:VTX:0:CMM:7706919:RAM:1171212:CPU:-1`

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.1

**Comment by oleksandrSydorenkoJ** [comment]
Not included in skaled: 3.17.0-beta.1

```
2023-06-22 11:44:06.817574   Block stats:BN:1216368:BTS:1687434222:TXS:16009:HDRS:11:LOGS:4486:SENGS:1:TXRS:4446:BLCKS:3:ACCS:150:BQS:1:BDS:1731:TSS:0:UTX:0:VTX:16000:CMM:4883261

```

**Comment by olehnikolaiev** [comment]
the cpu and ram usage is written in logs once per 1000 blocks. please recheck logs on block number 1217000

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression Network

Version:  3.17.0-beta.1
Chain name: wan-tasty-kitalpha

```
2023-06-22 11:31:18.019724   Block stats:BN:1216000:BTS:1687433445:TXS:16015:HDRS:11:LOGS:7471:SENGS:1:TXRS:7431:BLCKS:3:ACCS:150:BQS:1:BDS:2925:TSS:0:UTX:0:VTX:16000:CMM:7960227:RAM:573008:CPU:6.32594
```

**Comment by EvgeniyZZ** [comment]
Add link to the document that describe how calculated 
RAM:573008:CPU:6.32594
Add/update document with global meaning BN:- block nubmer?:BTS: block timestamp?

**Comment by oleksandrSydorenkoJ** [comment]
https://github.com/skalenetwork/internal-support/blob/main/docs/testing-space/skaled-consensus-clarification/consensus-logs-definition.md
