### ISSUE TITLE
Block finalization: logging improvements 

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/skaled#1530]
**Introduction**
Current logs is not enough to determine slow block finalization time if something went wrong. 

**Solution**
Based on this [document](https://github.com/skalenetwork/internal-support/blob/main/docs/testing-space/skaled-consensus-clarification/block-mining-procedure.md), split block processing to 3 stages:
- skaled
- consensus 
- sgx  

Each block should have information in ``loglevel: info``in this format: 
Example: BF: 1000 SD: 300 CS: 200 SX: 500, where 1000 - time in milliseconds 
Abbreviation(can be different): 
BF - Block Finalization total time of block finalization
SD - skaled time
CS - consensus time
SX - time for interaction with SGX server

**Comment by dimalit** [comment]
@EvgeniyZZ Probably it's time to ask: time between which two moments is considered "BF"?
@EvgeniyZZ Also, as these metrics are collected in different places (consensus and skaled) - it woulf be much easier to report these pieces of information on different log lines. Is this satisfactory solution?

**Comment by EvgeniyZZ** [comment]
@dimalit I'm assume that its related to ``transaction finality``. Thus, finality is the point where transactions on a blockchain are considered immutable. Finality is supposed to guarantee that transactions within a block cannot be altered. When transaction placed in specific block and validated. 

This information can be in different log lines and correspond  to same block.

**Comment by olehnikolaiev** [comment]
```
Abbreviation(can be different):
BF - Block Finalization total time of block finalization
SD - skaled time
CS - consensus time
SX - time for interaction with SGX server
```
new abbreviations:
BFT - block finalization time (time from block to block)
SWT - skaled work time (how much time sklaed spent to process txns and write everything to db)
CWT - consensus work time (how much time consensus takes after receiving txn list from skaled before consensus pushes new block to skaled)
SBPT - sgx block processing time (how much time consensus spends for sgx calls)
TLWT - txn list wait time (hom much time consensus waits to receive txn list from skaled)

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.1

**Comment by oleksandrSydorenkoJ** [comment]
Verified on regression network
Skale chain name: wan-tasty-kitalpha
Version: schain:3.17.0-beta.4
Log level skaled = -v 2 (info)
Log level consensus = info

Logs for empty block:
```
2023-07-04 10:21:42.024023   Block 1308755 DB usage is 1113. Piece DB usage is 9564009 bytes
2023-07-04 10:21:42.026901   SWT:3:BFT:11415
[2023-07-04 10:21:52.485] [7:main] [info] 1308755:CWT:1753:TLWT:8704:SBPT:441
```

Logs for block with transactions:
```
2023-07-04 10:22:04.895199   Block 1308763 DB usage is 7077. Piece DB usage is 9647853 bytes
2023-07-04 10:22:04.898582   SWT:54:BFT:1538
[2023-07-04 10:22:09.505] [7:main] [info] 1308763:CWT:4595:TLWT:11:SBPT:1937

```
