### ISSUE TITLE
Shutdown snapshot hash computation at exit

### ISSUE THREAD

**Issue by dimalit** [skalenetwork/skaled#1532]
When skaled is about to exit, it can happen that at the same time it's in the process of computing hash of snapshot. As this computation can take significantly long time (hours), we need to terminate this computation is some way. At next skaled start it should start snapshot hash computation all over again.
Also consider the case when skaled is computing hash of snapshot that it has just downloaded.

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.1

**Comment by OleksanderSalamatov** [comment]
Duplicate of https://github.com/skalenetwork/skaled/issues/1525
