### ISSUE TITLE
"Unexpected field 'storageDestructionPatchTimestamp' in config:" error after start skaled after update

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1557]
**Describe the bug**
Schain config contains storageDestructionPatchTimestamp options, that should be read by skaled 

**Preconditions**
Active schain medium type on 2.1.1. version skaled ``schain:3.16.1``

**Versions**
schain:3.17.0-beta.1
 

**To Reproduce**
1. Update Existing skaled from ``schain:3.16.1`` to schain:3.17.0-beta.1
2.  Check skaled logs

**Expected behavior**
Skaled should be compatible with storageDestructionPatchTimestamp option in the schain config 

**Actual state:**
Skaled crashes with the error in schain config 

**Logs:**

```
2023-06-21 15:42:35.870885   /home/ubuntu/actions-runner/_work/skaled/skaled/libdevcore/JsonUtils.cpp(68): Throw in function void dev::requireJsonFields(const mObject&, const string&, const std::map<std::__cxx11::basic_string<char>, std::pair<std::set<json_spirit::Value_type>, dev::JsonFieldPresence> >&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::UnknownField>
[dev::tag_comment*] = Unexpected field 'storageDestructionPatchTimestamp' in config: ChainParams::loadConfig::skaleConfig::sChain
```

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.2

**Comment by oleksandrSydorenkoJ** [comment]
Verified on 3.17.0-beta.7
no exceptions after creating skaled container
