### ISSUE TITLE
Skaled doesn't propose new blocks on updated node

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1559]
**Preconditions:**
Active schain medium type with MTM

**Versions:**
schain:3.17.0-beta.1

**To Reproduce**
1. Update one of 16 nodes to 3.17.0-beta.1
2. Check skaled logs - skaled on an updated node should propose every block
3. Run load on schain (token transfer) in a cycle for a 10 hours
4. Wait 10 minutes after starting the load and check the skaled logs
 
**Expected behavior**
Skaled on an updated node should send a proposal for every block

**Actual state:**
Skaled doesn't propose new blocks on the updated node.
After 5 minutes after receiving the first transactions - skaled stuck and stopped mining block at all

[skaled_not_propose_blocks_start.txt](https://github.com/skalenetwork/skaled/files/11835060/skaled_not_propose_blocks_start.txt)

[start_skaled_that_not_proposed.txt](https://github.com/skalenetwork/skaled/files/11835125/start_skaled_that_not_proposed.txt)

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.3

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.4

**Comment by oleksandrSydorenkoJ** [comment]
skaled: 3.17.0-beta.6 

Closed per fix in  https://github.com/skalenetwork/skaled/issues/1560 
The node without an actual block number is not allowed to propose the new blocks.
