### ISSUE TITLE
All skaled on 1 node crashed

### ISSUE THREAD

**Issue by dimalit** [skalenetwork/skaled#1581]
1 node has 3 schains. All crashed very close in time to each other.
Main symptom: seemingly while writing block to DB, skaled hangs. See stucks.csv
[stucks.csv](https://github.com/skalenetwork/skaled/files/11959603/stucks.csv)

Also, there appear another error messages:
```
[2023-07-04 00:16:20.725] [191:main] [error] 2794078:    !Caused by: CacheLevelDB:LevelDB:Could not write to database:IO error: /data_dir/blocks_191.db/db.5/008857.log: Input/output error
...
OpenSSLEdDSAKey:State check failed::encodedPubKeyBio /home/ubuntu/actions-runner/_work/skaled/skaled/libconsensus/crypto/OpenSSLEdDSAKey.cpp:158
...
CacheLevelDB:LevelDB:Could not write to database:IO error: /data_dir//proposal_hashes_191.db/db.6/001298.log: Read-only file system
```

**Comment by kladkogex** [comment]
IO error: /data_dir//proposal_hashes_191.db/db.6/001298.log: Read-only file system

Looks like a disk read/write problem

**Comment by PolinaKiporenko** [comment]
hard to reproduce
