### ISSUE TITLE
Skaled tries to send 0-block snapshot if not all nodes online 

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1587]
**Describe the bug**
Skaled should contain snapshots with the 0 block (if schains gen2) and 2-3 snapshots with the actual block numbers

**Versions**
schain:3.17.0-beta.5

**To Reproduce**
1. Stop 6 nodes 
2. turn on 1st one of stopped nodes from the snapshot - should failed without majority of nodes
3. turn on 2nd stopped node from the catchup
4.  wait for 3 hours of consensus downtime 
5. restart 1st node from the snapshot again

**Expected behavior**
Skaled on the 1st stopped node should download  actual snapshot block number

**Actual state:**
Node sender sends 0-block number snapshot to the node 1st stopped node (receiver of the snapshot) 

**Logs**
[0-block-after-downtime.log](https://github.com/skalenetwork/skaled/files/12016912/0-block-after-downtime.log)

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network 

schain:3.17.0-beta.7




[snapshot_1587.log](https://github.com/skalenetwork/skaled/files/12437417/snapshot_1587.log)

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.6
