### ISSUE TITLE
Skaled crashes after state root mismatch error and exit with 137 ExitCode 

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1613]
**Preconditions:**
Active schain medium type 16 nodes 
Skale schain name: wan-tasty-kitalpha

**Versiosns**
skalenetwork/schain:3.17.0-beta.6

**Stpes to reproduce:**
1. Connect to any node via ssh and create random file in schain datadir
2. wait 2 snapshot interval 
3. check skaled logs 

**Expected state:**
Skaled should catch state root error, set restart from the snapshot in skaled status file and exit with 200 exit Code 

**Actual state:**
Skaled crashes after catching state root error 

**Logs:**
skaled status file:
```
root@ip-172-31-56-65:~# cat .skale/node_data/schains/wan-tasty-kitalpha/skaled.status 
    {
       "subsystemRunning":{
           "SnapshotDownloader": false,
           "WaitingForTimestamp": false,
           "Blockchain": true,
           "Rpc": true
       },
       "exitState":{
           "ClearDataDir": false,
           "StartAgain": true,
           "StartFromSnapshot": false,
           "ExitTimeReached": false
       }
    }

```

docker container
```
efd793427cd8   skalenetwork/schain:3.17.0-beta.6               "/skaled/skaled --co…"   2 hours ago    Exited (134) 6 minutes ago                                                        skale_schain_wan-tasty-kitalpha

```
Logs from skaled 
[skaled_crashes_after_state_root_error.txt](https://github.com/skalenetwork/skaled/files/12260533/skaled_crashes_after_state_root_error.txt)

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.8

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network 
skale_schain_free-basic-rosy-SKALE
skaled: 3.17.0-beta.8



[state_root_exit_verification.log](https://github.com/skalenetwork/skaled/files/12562676/state_root_exit_verification.log)
