### ISSUE TITLE
RPC does not set `Content-Type` HTTP header

### ISSUE THREAD

**Issue by jxom** [skalenetwork/skaled#1619]
**Describe the bug**
Skale RPC Providers do not set the `Content-Type` header to `application/json`. This consequently [confuses consuming clients](https://github.com/wagmi-dev/viem/blob/2c666f452968e349a839344ee563331e20e6fdad/src/utils/rpc.ts#L107-L111) as they don't know if they should parse the response as JSON, or raw text.

**Steps to reproduce**
Check the HTTP response headers of `https://mainnet.skalenodes.com/v1/honorable-steel-rasalhague`

```bash
curl -v https://mainnet.skalenodes.com/v1/honorable-steel-rasalhague
```

**Expected behavior**
The RPC Provider should set the HTTP response header `Content-Type` to `application/json`.

**Additional context**
See https://github.com/wagmi-dev/viem/issues/910

**Comment by DmytroNazarenko** [comment]
Verified on devnet, 3.18.0-develop.9:
```
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Date: Tue, 24 Oct 2023 18:04:46 GMT
< Connection: keep-alive
< Content-Length: 151
```

**Comment by DmytroNazarenko** [comment]
skaled: 3.18.0-beta.0

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Regression network
schain: aged-wry-finished-skale
skalenetwork/schain:3.18.0-beta.0

```
curl -X POST --data '{"id":4,"jsonrpc":"2.0","method":"eth_pendingTransactions","params":[]}'   -v https://regression-node0.skaleserver.com:10072

* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Date: Wed, 24 Jan 2024 19:02:19 GMT
< Connection: keep-alive
< Content-Length: 36
< 
* Connection #0 to host regression-node0.skaleserver.com left intact
{"id":4,"jsonrpc":"2.0","result":[]}

```
