### ISSUE TITLE
Issue with using block.chainid in Solidity

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/skaled#1627]
**Describe the bug**
When using block.chainid in Solidity it always returns 1. 
This breaks compatability with certain standards such as EIP-712.

**To Reproduce**
1. Create a smart contract
2. Use block.chainid in Solidity
3. See it always returns 1
4. Error if using EIP-712 is that it returns invalid hash

**Expected behavior**
It should return the correct chainid for each SkALE Chain

**Comment by PolinaKiporenko** [comment]
@payvint please add more details

**Comment by PolinaKiporenko** [comment]
@TheGreatAxios please check if it still relevant

**Comment by DmytroNazarenko** [comment]
Close as not reproducible per @TheGreatAxios
