### ISSUE TITLE
Improve data destruction in Level DB

### ISSUE THREAD

**Issue by PolinaKiporenko** [skalenetwork/skaled#1644]
There was an ineffective algorithm for data destruction in EVM that got fixed.

We iterate over LevelDB keys belonging to the account that has been destroyed and remove them

@kladkogex please add more description

**Comment by kladkogex** [comment]
There are two levels at which data 
destruction happens:

1) EVM call delete keys of LevelDB - there was a bug in this that has been fixed. Note that there is a patch that needs to be enabled.

2) If keys are destroyed, sometimes LevelDB does not shrink the LevelDB file where the keys are stored. This is a separate problem
