### ISSUE TITLE
Move tracing API to a separate JSON RPC server

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skaled#1741]
Move tracing API to a separate JSON RPC server inside SKALED

**Comment by olehnikolaiev** [comment]
blocked by tracing epic

**Comment by DmytroNazarenko** [comment]
Moved to 2.5 as non-critical

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Legacy network 
skalenetwork/schain:3.20.0-beta.1-historic

[tracing_report_3.20.0-beta.1.txt](https://github.com/user-attachments/files/17667420/tracing_report_3.20.0-beta.1.txt)
