### ISSUE TITLE
Skaled doesn't support default tracer on archive node

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1764]
**Preconditions**
Active chains
Archival node
Deployed contract with erc20 tokens

**Versions**
skalenetwork/schain:3.17.2-develop.2-historic

**Steps to reproduce**
1. Send transaction to schain
2. Send debug_traceTransaction method with callTracer tracer
3. Send debug_traceTransaction method without any tracers

**Expected state:**
Skaled without any tracers should return a general overview of the transaction execution. 

**Actual state:**
Skaled return ann error: 
```
Response traceCall: {"error":{"code":-32602,"message":"INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised"},"id":1,"jsonrpc":"2.0"}
```

**Example**
```
{'jsonrpc': '2.0', 'method': 'debug_traceTransaction', 'params': ['0x8c4db9caf5ba62627e36d2ce20aa9da865f4f080e425fd629779c14fa5aabab7', {'tracer': 'callTracer'}], 'id': 1}

{'jsonrpc': '2.0', 'method': 'debug_traceTransaction', 'params': ['0x8c4db9caf5ba62627e36d2ce20aa9da865f4f080e425fd629779c14fa5aabab7'], 'id': 1}
```

**Comment by kladkogex** [comment]
To run default tracer you need to do something like 

{'jsonrpc': '2.0', 'method': 'debug_traceTransaction', 'params': ['0x8c4db9caf5ba62627e36d2ce20aa9da865f4f080e425fd629779c14fa5aabab7', {'}], 'id': 1}

So {} is needed

Marking this as incomplete

**Comment by oleksandrSydorenkoJ** [comment]
> To run default tracer you need to do something like
> 
> {'jsonrpc': '2.0', 'method': 'debug_traceTransaction', 'params': ['0x8c4db9caf5ba62627e36d2ce20aa9da865f4f080e425fd629779c14fa5aabab7', {'}], 'id': 1}
> 
> So {} is needed
> 
> Marking this as incomplete

The consequence of https://github.com/skalenetwork/skaled/issues/1751 
Even with empty brackets after transaction hash in params skaled doesn't return the expected response 
JSON-RPC debug method request to block contains several transactions from a single user 
```
curl  http://localhost:10131   -X POST  -H "Content-Type: application/json" --data '{"id":1,"jsonrpc":"2.0","method":"debug_traceTransaction","params":["0xf27ac6fa8f34479d97331534d90b6a120d3c510c8645506b67d506cc00de83fe", {}]}'
{"error":{"code":0,"data":null,"message":"State check failed::m_topFunctionCall /home/s5/actions-runner-3/_work/skaled/skaled/libhistoric/AlethStandardTrace.cpp:374"},
```

**Comment by oleksandrSydorenkoJ** [comment]
> To run default tracer you need to do something like
> 
> {'jsonrpc': '2.0', 'method': 'debug_traceTransaction', 'params': ['0x8c4db9caf5ba62627e36d2ce20aa9da865f4f080e425fd629779c14fa5aabab7', {'}], 'id': 1}
> 
> So {} is needed
> 
> Marking this as incomplete

Default tracer is supported in skalenetwork/schain:3.17.2-develop.3-historic
```
 curl http://localhost:10131 -X POST -H "Content-Type: application/json" --data '{"method":"debug_traceTransaction","params":["0x14587e796a905cb02021daf3a52ab1fc3731cb3de569ffc94645fa3a756ff771",{}],"id":1,"jsonrpc":"2.0"}'
{"id":1,"jsonrpc":"2.0","result":{"from":"0xa68f946090c600eda6f139783077ee802afeb990","gas":"0x2344060","gasUsed":"0x3ee297","input":"0x47237f47000000000000000000000000000000000000000000000000000000000000061a","to":"0xb94c8d344497feceda232e6870d0fd16cec4f175","type":"CALL","value":"0x0"}}
```

The required empty object in debug methods should be fixed in a separate issue https://github.com/skalenetwork/skaled/issues/1780
