### ISSUE TITLE
Fix net_version test

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1811]
Unit test in skaled `jsonrpc_netVersion` randomly fails on check

```BOOST_CHECK_EQUAL( version, "65535" );```

Need to fix it to make all tests passed on Github Actions

**Comment by DmytroNazarenko** [comment]
skaled: 3.18.0-beta.0

**Comment by PolinaKiporenko** [comment]
3.18.1-beta.0
