### ISSUE TITLE
go-ethereum>=1.13.0 is not compatible because `eth_call` API has changed (`data` became `input` for call arguments)

### ISSUE THREAD

**Issue by Darkness4** [skalenetwork/skaled#1825]
**Describe the bug**

Hi, it seems that `go-ethereum` has decided to use the `input` field instead of the `data` field on their JSON-RPC client. It would be great if SKALE could support the `input` field and still be backwards compatible. Apparently, the [specs changed 6 years ago](https://github.com/ethereum/go-ethereum/issues/28608#issuecomment-1827273566). I don't know what other changes have been added.

Relevent issues: https://github.com/ethereum/go-ethereum/issues/28608, https://github.com/ethereum/go-ethereum/pull/28078 and https://github.com/ethereum/go-ethereum/issues/15628

Revelent docs: 
- JSON-RPC specs: https://github.com/ethereum/execution-apis
  - `eth_call`: https://github.com/ethereum/execution-apis/blob/4b225e0d273e92982b2c539d63eaaa756c5285a4/src/eth/execute.yaml#L1
  - Transaction Object: https://github.com/ethereum/execution-apis/blob/4b225e0d273e92982b2c539d63eaaa756c5285a4/src/schemas/transaction.yaml#L358
- JSON-RPC specs on ethereum.org: https://ethereum.org/developers/docs/apis/json-rpc#eth_call
- Go Implementations: 
  - Client: https://github.com/ethereum/go-ethereum/blob/95741b18448aaacacd0edd8f73a9364bd3df8c92/ethclient/ethclient.go#L642
  - Server: https://github.com/ethereum/go-ethereum/blob/95741b18448aaacacd0edd8f73a9364bd3df8c92/signer/core/apitypes/types.go#L82-L101
- skaled server implementation (maybe, I'm not sure): https://github.com/skalenetwork/skaled/blob/bdf02303c6703688f94a0e950d65557463fd7172/libweb3jsonrpc/JsonHelper.cpp#L460-L490

**To Reproduce**
1. `eth_estimateGas`, `eth_call`... with go-ethereum 1.13.0.
2. Gas estimation throws `EVM revert instruction without description message`

**Expected behavior**
1. Launch a transaction/call.

**Comment by DmytroNazarenko** [comment]
Hi @Darkness4 ! Thanks for reporting this issue, it is addressed to the following release

**Comment by PolinaKiporenko** [comment]
skaled:3.19.0-beta.0

**Comment by oleksandrSydorenkoJ** [comment]
Network Regression
Skale_schain carefree-knowing-sarin
skaled:3.19.0-beta.1



Example contract
```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.8.20;

contract Push0Test {
    function f() public pure returns (uint256){
        return 1;
    }
}

```
Example  request "input" and "data"
```
 curl http://localhost:10067   -X POST   -H "Content-Type: application/json"   --data '{"id":1610870259,"jsonrpc":"2.0","method":"eth_call","params":[{"input":"0x26121ff0","from":"0x71cBE3fedE33905d4D1Bf2Bd51f9d4A62375e659","to":"0xA4cE8db7791E107a46615231F8DAe594d552aA35","value":"0x0"},"latest"]}'  
 
{"id":1610870259,"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000001"} 

curl http://localhost:10067   -X POST   -H "Content-Type: application/json"   --data '{"id":1610870259,"jsonrpc":"2.0","method":"eth_call","params":[{"data":"0x26121ff0","from":"0x71cBE3fedE33905d4D1Bf2Bd51f9d4A62375e659","to":"0xA4cE8db7791E107a46615231F8DAe594d552aA35","value":"0x0"},"latest"]}'  

{"id":1610870259,"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000001"}
```

estimate_gas
```
curl http://localhost:10067   -X POST   -H "Content-Type: application/json"   --data '{"id":7,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x71cBE3fedE33905d4D1Bf2Bd51f9d4A62375e659","gasPrice":"0x186a0","input":"0x","nonce":"0xa4c","to":"0x71cBE3fedE33905d4D1Bf2Bd51f9d4A62375e659","value":"0x0"}]}'  

{"id":7,"jsonrpc":"2.0","result":"0x5208"}

 curl http://localhost:10067   -X POST   -H "Content-Type: application/json"   --data '{"id":7,"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x71cBE3fedE33905d4D1Bf2Bd51f9d4A62375e659","gasPrice":"0x186a0","data":"0x","nonce":"0xa4c","to":"0x71cBE3fedE33905d4D1Bf2Bd51f9d4A62375e659","value":"0x0"}]}'  

{"id":7,"jsonrpc":"2.0","result":"0x5208"}
```
