### ISSUE TITLE
Oracle verify transaction causes state root mismatch on archive node

### ISSUE THREAD

**Issue by OleksanderSalamatov** [skalenetwork/skaled#1836]
When oracle verify transaction is called, skaled takes data from `skaleConfig.nodeInfo.wallets.ima.n` field in schain config, which contains number of nodes in group. This field is present on all core nodes, but absent on archive node.

Skaled version: `3.18.0/3.18.0-historic`

Logs:
```
2024-02-26 15:25:59.236385   Exception in precompiled/getConfigVariableUint256(): Security poicy violation, inaccessible configuration JSON path: skaleConfig.nodeInfo.wallets.ima.n

2024-02-26 15:25:59.236482   Error message from eth_call(): Get config uint256 failed
```
```
archive: 2024-02-27 18:58:15.393818   Block sealed #1512602 (#7b0c6dbf…)
core:    2024-02-27 18:58:13.830707   Block sealed #1512602 (#2b5ccb19…)
```

**Comment by PolinaKiporenko** [comment]
will be fix via https://github.com/skalenetwork/skale-admin/issues/1050

**Comment by OleksanderSalamatov** [comment]
Resolved via changes in admin
