### ISSUE TITLE
Add support of different patchTimestamps for different chains

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skaled#1879]
We need to be able to set patch timestamps for specific chains in skale-node

**Comment by PolinaKiporenko** [comment]
3.19.0-beta.0

**Comment by oleksandrSydorenkoJ** [comment]
Verified on regression network 

https://github.com/skalenetwork/skale-node/blob/f40b562b14e7fdaadad69082a2e33f9a22a1d20d/static_params.yaml#L52
