### ISSUE TITLE
Memory leaks in Skaled under significant load 

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1919]
Related to https://github.com/skalenetwork/skaled/issues/1774

**Versions**
skalenetwork/schain:3.19.0-beta.1

**Preconditions**
8 Active schain medium type on 16 nodes (2 SGX)
at least 13 active nodes 
[Example contract](https://github.com/skalenetwork/SkaleExperimental/blob/master/s1/docker_loader/ERC20Custom.json)
tool for load test erc20 token transfer:
- 1000 users
- 15 mill gas usage 
- 125 kb block size in bytes
Tools for collecting RSS, CPU, SWAP, Network speed

**Steps to reproduce**
1. Run load test for 24 hours on 1 chain 
2. Check metrics and resource usage for the chain 

**Expected state**
RSS and CPU usage should be in a 2.5GB limit, without Swap usage. CPU usage less then 1/8 of total % 

**Actual state** 
RSS grows up to 2.6 GB, SWAP usage exceeds 2.6 GB and it leads to OOM error

![image](https://github.com/skalenetwork/skaled/assets/84327300/8d5b5efe-b754-4326-bec6-884737ccd9e3)
![image](https://github.com/skalenetwork/skaled/assets/84327300/de6a3a01-5857-478b-9780-62192a4adc2a)

**Comment by DmytroNazarenko** [comment]
skaled: 3.19.0-beta.2

**Comment by oleksandrSydorenkoJ** [comment]
Reproducible only under significant loda
skalenetwork/schain:3.19.0-beta.2
skale_schain_carefree-knowing-sarin

16 Mb every block
270kk gas usage 

![Image](https://github.com/skalenetwork/skaled/assets/84327300/208fb236-0ea1-43da-a445-fd692e75bc8e)
![Image](https://github.com/skalenetwork/skaled/assets/84327300/1adb0b2e-44cc-4637-a523-bbd98b0c0aaf)



Erc20 token transfer 
47kk ggas Usage
128KB block size 

![Image](https://github.com/skalenetwork/skaled/assets/84327300/d321ed45-bbc6-4731-8077-96ba4e4ccf2a)
![Image](https://github.com/skalenetwork/skaled/assets/84327300/c822c371-3061-44c0-ad61-4f8c4c1c3f20)
