### ISSUE TITLE
Skaled couldn't connect to majority of nodes and restarts after schain creation

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skaled#1921]
**Version:**
skalenetwork/schain:3.19.0-beta.1
skalenetwork/schain:3.18.2

**Preconditions**
16 active nodes  
13 nodes with versions skaled 3.19.0-beta.1
3 nodes with 3.18.2

**Steps to reproduce**
1. Create 1 schain 
2. Check skaled logs on nodes with versions skaled 3.19.0-beta.1
3. Wait for 20 minutes and re-check again logs on nodes with versions skaled 3.19.0-beta.1

**Expected state**
Skaled should start mining blocks in 20 seconds after schain container creation.  

**Actual state**
Skaled on updated nodes 3.19.0-beta.1 could not connect to other updated nodes and is able to connect to 3 not upgraded nodes on version 3.18.2. 
After 20 minutes of downtime skaled restarts and start mining blocks.
Skale admin received the error on the valid  eth_getBlockByNumber request
```
2024-06-12 12:29:18.743602   http://127.0.0.1:34376 >>> {"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false]}
2024-06-12 12:29:18.743891   http://127.0.0.1:34376 <<< {"error":{"code":-32602,"data":null,"message":"INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised"},"id":1,"jsonrpc":"2.0"}
2024-06-12 12:29:45.000490   http://127.0.0.1:35918 >>> {"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest",false]}
```
13/16 - 3.19.0-beta.1 version
3/16 - 3.18.2 version 
[skaled_3_18_2_start_schain_creation.txt](https://github.com/user-attachments/files/15900582/skaled_3_18_2_start_schain_creation.txt)
[skaled_3_19_0_beta_1_could_not_start_13_of_16.txt](https://github.com/user-attachments/files/15900583/skaled_3_19_0_beta_1_could_not_start_13_of_16.txt)

all 16 nodes on 3.19.0 version
[skaled_3_19_0_beta-1_schain_creation.txt](https://github.com/user-attachments/files/15900581/skaled_3_19_0_beta-1_schain_creation.txt)

**Comment by olehnikolaiev** [comment]
seems like the updated nodes couldn't be pinged right after the schain creation. after the restart they were successfully pinged by other nodes and skaled started working

**Comment by oleksandrSydorenkoJ** [comment]
not actual for skalenetwork/schain:3.19.0-beta.2
