### ISSUE TITLE
Revert in Solidity is not returning data

### ISSUE THREAD

**Issue by TheGreatAxios** [skalenetwork/skaled#1931]
In Solidity, the usage of revert should return **data** with the error.
However, it currently only returns a message "EVM Revert instruction without description".

## Example 1
```shell
curl --location 'https://testnet.skalenodes.com/v1/lanky-ill-funny-testnet' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "id": 2,
    "method": "eth_call",
    "params": [
        {
            "data": "0x9b249f69000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000589406Cc6185a346906296840746125a0E449764545fbfb9cf0000000000000000000000004b4888942bfe98731727d0955cdd42cbecf3dd1900000000000000000000000000000000000000000000000000000000000000000000000000000000",
            "to": "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789"
        },
        "latest"
    ]
}'
```

```shell
# Bad Response
{
    "error": {
        "code": -32000,
        "message": "EVM revert instruction without description message"
    },
    "id": 2
}```

```shell
# Expected Response
{
    "jsonrpc": "2.0",
    "id": 31,
    "error": {
        "code": 3,
        "message": "execution reverted",
        "data": "0x6ca7b806000000000000000000000000bef40b38488565c26f99919ffd257971e01740c9"
    }
}
```

## Example 2
SKALE Response: https://app.warp.dev/block/1pL1PAVLouh2XQmUhVkk87
Polygon Response: https://app.warp.dev/block/pgloOFabissEG6rlZheIja

**Comment by jflatow** [comment]
I can confirm this is blocking our AA bundler from being able to integrate with their infrastructure, as they expect to be able to get revert reason from return data

**Comment by TheGreatAxios** [comment]
Confirming that partners can utilize Indexer node as temporary solution

**Comment by PolinaKiporenko** [comment]
Hotfix with update on stable skaled v3 only for Indexer and Archive nodes, then will be available on core nodes in 3.1 release

**Comment by jflatow** [comment]
> Hotfix with update on stable skaled v3 only for Indexer and Archive nodes, then will be available on core nodes in 3.1 release

That's great, doest that mean this is available on some nodes now?

**Comment by PolinaKiporenko** [comment]
@jflatow Hello, we will add this functionality to the Indexer and Archive nodes once we release V3 on the Mainnet (ETA end of July)

**Comment by EvgeniyZZ** [comment]
Verified:
skaled core: 3.19.1-beta.0
The response from Schain are correct, but less complete and informative. 
Ethereum  provides more complete information about the type of error and is commonly used in libraries such as web3.j/ethers.js.

Contract: 
pragma solidity ^0.8.0;

contract Revert {
    function checkBalance(uint balance, uint amount) public pure {
        if (balance < amount) {
            revert("Insufficient balance");
        }
    }
}
Request to Ethereum(Holesky):
``curl -X POST --data '{"id":"a14b6304-befc-42f2-890c-7d0e22a3a5e2","jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xE52674Dbc158D4a2449c2D6528aCE9262b4db305","data":"0xb471f40a000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000002"},"latest"]}'  http://put-holesky-endpoint:8545 -H "Content-Type: application/json"``
Response from Ethereum:
``{"jsonrpc":"2.0","id":"a14b6304-befc-42f2-890c-7d0e22a3a5e2","error":{"code":3,"message":"execution reverted: Insufficient balance","data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000014496e73756666696369656e742062616c616e6365000000000000000000000000"}}``



Request to Schain: 
``curl -X POST --data '{"id":"a14b6304-befc-42f2-890c-7d0e22a3a5e2","jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x258CbDf60dE0C50803898Eb965b1F30feb97D01d","data":"0xb471f40a000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000002"},"latest"]}'  http://64.176.38.72:10067/ -H "Contentype: application/json"``
Response from schain: 
``{
   "error":{
      "code":3,   "data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000 
 000000000000000000000000000000014496e73756666696369656e742062616c616e6365000000000000000000000000",
      "message":"Insufficient balance"
   },
   "id":"a14b6304-befc-42f2-890c-7d0e22a3a5e2",
   "jsonrpc":"2.0"
}``
