### ISSUE TITLE
go-ethereum fails to decode transaction from block 1527619 on Nebula Testnet

### ISSUE THREAD

**Issue by taylanpince** [skalenetwork/skaled#1959]
**Describe the bug**
We are having trouble parsing a specific transaction on Nebula Testnet due to missing `chainId` data in the txn.

**To Reproduce**
Run the following request:

```
curl -X 'POST' -d '{"jsonrpc":"2.0","id":8,"method":"eth_getBlockByNumber","params":["0x174f43",true]}' -H 'Content-Type: application/json' -H 'User-Agent: sequence/node-check' 'https://lanky-ill-funny-testnet-indexer.skalenodes.com:10136/'
```

Note that the transaction of type `0x02` has no `chainId` attribute.

**Expected behavior**
`chainId` is a required attribute for all transactions.

**Additional info**
For transactions of type "Dynamic Fee", `chainId` is a required attribute: https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction_marshalling.go#L277-L279

**Comment by EvgeniyZZ** [comment]
Verified: 
Skaled core: 3.19.1-beta.0
Request to Schain: 
``curl -X 'POST' -d '{"jsonrpc":"2.0","id":8,"method":"eth_getBlockByNumber","params":["0x61en",true]}' -H 'Content-Type: application/json' -H 'User-Agent: sequence/node-check' 'http://64.176.38.72:10067'``

{"id":8,"jsonrpc":"2.0","result":{"author":"0xd2ba3e0000000000000000000000000000000000","baseFeePerGas":"0x186a0","boundary":"0x0000000000000000000000000000000000000000000000000000000000000000","difficulty":"0x0","extraData":"0x736b616c65","gasLimit":"0xfffffff","gasUsed":"0x2d4a6","hash":"0x083429d2624243ebbeb7b9d19c5f28282f047b26ed627eba169414c17e0731fc","logsBloom":"0x00000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000080000080000100000000000000008000000000000002040000200000000000000000000000000020000400000000000000800000000004000000000000010000000000000000000000000000000000000000000000000000040000000000000000000004000000000000000000000000000020000000000000000000000000000000000000002000000000800001000400000000000000000000000000000000020000000001000000400000000200000044000000000000000000000000000000004","miner":"0xd2ba3e0000000000000000000000000000000000","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":"0x61e","parentHash":"0x903aa2bc9a7187ded70b4ab71e71254ef852e68dd6128d1902e664159f47a1c6","receiptsRoot":"0x631f39190d4e571c642ac0be19f8c6404474be371f47f897fd366772979b838d","seedHash":"0x0000000000000000000000000000000000000000000000000000000000000000","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x277","stateRoot":"0x8b73318a1ae39a3a12b385d295b4e08a47a0388ccc95c82ff2c29a7649f5a6c5","timestamp":"0x66cf54ed","totalDifficulty":"0x0","transactions":[{"accessList":[],"blockHash":"0x083429d2624243ebbeb7b9d19c5f28282f047b26ed627eba169414c17e0731fc","blockNumber":"0x61e",**"chainId":"0x54d67625"**,"from":"0x47a260715623df37b9f5ea52c2e66245c0529df2","gas":"0x37f96","gasPrice":"0x2d23c11e2","hash":"0xc23f78fcea49082b7034d625d5d010e15a355f1b9cb65076178ccfd59a95d398","input":"0xeeeb9601000000000000000000000000000000000000000000000000000000e8d4a51000","maxFeePerGas":"0x2d23c11e2","maxPriorityFeePerGas":"0x55d4a80","nonce":"0x2","r":"0xeead836a2034d1dfef4311cf5069571ba75b966837cbb03908556f1e5b904176","s":"0x1cea05b333d068e5f1ed607e89affaa35d773657ab31ad68296bd8ce7b0c1d79","to":"0xd2aaa00400000000000000000000000000000000","transactionIndex":"0x0","type":"0x2","v":"0xa9acec6d","value":"0x0","yParity":"0x0"}],"transactionsRoot":"0x3720299160036d2aa46542a9b0ebfa69f118e10ecfd223aff9080827be401482","uncles":[]}}

**Comment by taylanpince** [comment]
After the upgrade, we are now getting a different error on the same block: `Error: 'v' and 'yParity' fields do not match`

ethkit is still unable to parse and we remain stuck.
