### ISSUE TITLE
eth_estimateGas uses chainId `50000000` instead of the chains actual chainId

### ISSUE THREAD

**Issue by mouseless0x** [skalenetwork/skaled#1976]
**Describe the bug**

For ERC-4337 transactions, the chainId is used for signature validation onchain and upon investigation I discovered that the chainId being used during eth_estimateGas is 50000000. 

This behaviour is unexpected because it causes eth_estimateGas calls to revert whilst running the exact same call through eth_call succeeds (eth_call uses the chain's actual chainId so it doesn't have this problem)

I found out that the chainId is 50000000 during eth_estimateGas using this:
https://gist.github.com/mouseless-eth/ee3f94c619e7b5e43035e86cbcb360a9

**Expected behavior**
eth_estimateGas should use the chains actual chainId

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Legacy network 
skalenetwork/schain:3.19.2-beta.0
Skale chain: black-spherical-graffias
chainId 0x0000028d08095 
```
:test_estimate_gas_chain_id 
{'jsonrpc': '2.0', 'id': 4337, 'method': 'eth_estimateGas', 'params': [{'from': '0x71cBE3fedE33905d4D1Bf2Bd51f9d4A62375e659', 'data': '0x6080604052348015600f57600080fd5b50604051633013bad360e21b815246600482015260240160405180910390fdfe'}, '0x2DFCA4']}

2024-09-16 17:25:39 [    INFO] {'code': 3, 'data': '0xc04eeb4c0000000000000000000000000000000000000000000000000000000028d08095', 'message': 'EVM revert instruction without description message'}
2024-09-16 17:25:39 [    INFO] 0x28d08095 
```
