### ISSUE TITLE
Delays in Transaction Confirmations Causing Failures

### ISSUE THREAD

**Issue by Yashk767** [skalenetwork/skaled#2002]
### Describe the bug:
We are experiencing significant delays in transaction confirmations, approximately 30 seconds, which is causing failures due to the state expiration in our contracts.

Even though the transactions are confirmed on-chain about 30 seconds after they are sent, the explorer shows a confirmation time of <= 7.273 seconds. This discrepancy is affecting our contract logic, as the transactions are being mined too late, beyond the expected state time frame.

#### Affected Blocks:

[Block 6628123](https://elated-tan-skat.explorer.mainnet.skalenodes.com/block/6628123)
[Block 6615052](https://elated-tan-skat.explorer.mainnet.skalenodes.com/block/6615052)
[Block 6664300](https://elated-tan-skat.explorer.mainnet.skalenodes.com/block/6664300)
[Block 6664218](https://elated-tan-skat.explorer.mainnet.skalenodes.com/block/6664218)

#### Additional Information 

Along with the failed transactions included in the mentioned blocks, there were also successful transactions sent around the same time. However, while the failed transactions were confirmed with a delay of more than 30 seconds, the successful transactions were confirmed almost instantly in the blocks prior to the ones containing the failed transactions.

### Expected Behavior:
Usually the transactions gets confirmed within ~7 seconds in all the scenarios and even in these occurrences these failed transactions should have been confirmed within the expected regular time frame, and the time taken for the node to receive the mined transaction receipt should closely match the reported explorer confirmation time.

### Logs
Provided the logs with timestamps for failed transactions in block[ 6664218](https://elated-tan-skat.explorer.mainnet.skalenodes.com/block/6664218?tab=txs) when they were sent from our node -
https://docs.google.com/document/d/17kXPHluVm8uSaq48_pxmKEaqgG6VwKLXANMr1rTcdCQ

**Comment by TheGreatAxios** [comment]
Direct endpoints were provided to the dev team to allow exploration on whether it could have been a slow down of a singular node and/or proxy at any given point in time.

**Comment by PolinaKiporenko** [comment]
not reproducible
