### ISSUE TITLE
Question: Async functionality in libskutils/include/httplib.h

### ISSUE THREAD

**Issue by yhirose** [skalenetwork/skaled#219]
Hi, I am an author of [cpp-httplib](https://github.com/yhirose/cpp-httplib) HTTP library, and I am happy to see you are using it in your project.

A user just asked me to provide 'non-blocking' APIs in cpp-httplib, but it looks requiring lots of changes. But I just happened to find your fork of cpp-httplib looks supporting **async** functionality without changing the existing APIs in the beautiful way.  I am not planning to make any change to my cpp-httplib in this regard, but I just wonder if your fork could work perfectly in the user's project.

If your fork is specialized only for your project, or is it more like a general async http library? Thanks!

https://github.com/yhirose/cpp-httplib/issues/379

**Comment by sergiy-skalelabs** [comment]
> Hi, I am an author of [cpp-httplib](https://github.com/yhirose/cpp-httplib) HTTP library, and I am happy to see you are using it in your project.
> 
> A user just asked me to provide 'non-blocking' APIs in cpp-httplib, but it looks requiring lots of changes. But I just happened to find your fork of cpp-httplib looks supporting **async** functionality without changing the existing APIs in the beautiful way. I am not planning to make any change to my cpp-httplib in this regard, but I just wonder if your fork could work perfectly in the user's project.
> 
> If your fork is specialized only for your project, or is it more like a general async http library? Thanks!
> 
> [yhirose/cpp-httplib#379](https://github.com/yhirose/cpp-httplib/issues/379)



Hi, yes we did. Thanks for your HTTP(S) implementation. It just works perfect.
We added async functionality in modified version of your HTTP lib by calling our **libskutls** library. Last one contains **dispatch** class that implements task management similar to Apple's **Grand Central Dispatch**. But our dispatch is more dedicated to server side tasks and that is why it's based on thread pool with pre-initialized thread count. This **dispatch** is using **libuv**. Basically dispatch provides async multi-threading and prevents creation of too much threads.
When your HTTP server code accepts client connection - we move its handling into **dispatch** sequence of tasks. So connection acceptor is free to handle more connections.
See **read_and_close_socket_async()** method for details.
Our for is for our one project only.

**Comment by yhirose** [comment]
@sergiy-skalelabs, thank you very much for the detail. I am amazed to see what you have done in cpp-httplib! It's a great idea to use libuv to accomplish async/non-blocking functionality. I feel your implementation is much better than my original multi-thread approach for large scale serious server tasks such as the c10k problem. Thanks for your answer!

**Comment by StevenBarnett1** [comment]
Hey guys, I’m implementing cpp-httplib right now and I had some questions about the async / non blocking functionality.

my app has a single route which does a sql query (IO blocking), then a lot of CPU blocking tasks parallelized  with open MP. 

I’m struggling to understand if your “non blocking” version of httplib will prevent threads from blocking during IO blocking actions like sql queries? 

If I have 5 threads and each of them are handling a request and they are all in the middle of waiting for sql queries to finish, if a 6th request comes in will it be handled immediately and begin making its sql query? Or will one of those threads need to finish?

Furthermore, if it has to wait for those threads to finish, then how is this non blocking? 

Thank you!
