### ISSUE TITLE
ERC721 Interaction Issues

### ISSUE THREAD

**Issue by christineRPM** [skalenetwork/skaled#446]
Posting issue reported by CryptoRaves (@cartosys):

Hi Christine,

I've recently encountered an error while working on the "BoB" testnet. I've ran the same suite of tests before without encountering an issue, so I suspect something has changed on the Skale side in recent weeks. 

Here is what i've tracked it down as well as a brief description:

When depositing an ERC721 standard token into a custom smart contract I get the following error:

Wed Jan 27 01:54:32 PM EST 2021:  <- I ran this on Bob within a few seconds of this time

Transaction: 0x81be80025ed66260e8fd180f85515d484f0163aafeec1d0219f00878bece7084 exited with an error (status 0) after consuming all gas.
     Please check that the transaction:
     - satisfies all conditions set by Solidity `assert` statements.
     - has enough gas to execute the full transaction.
     - does not trigger an invalid opcode by other means (ex: accessing an array out of bounds).
  StatusError: Transaction: 0x81be80025ed66260e8fd180f85515d484f0163aafeec1d0219f00878bece7084 exited with an error (status 0) after consuming all gas.
      at Context.<anonymous> (test/erc721Test.test.js:11:28)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

I've tried to increase the gas limit in the truffle-config. Here is my configuration for Bob testnet:

skaleTestBob: {
        provider: () => new HDWalletProvider(privateKey, 'https://dev-testnet-v1-1.skalelabs.com'),
        gasPrice: 0,
        gas: 160000000,  // <- this # is greatly increased from when it worked before
        network_id: "*",
        timeout: 100000,
        ChainID: 344435
      },

Below is the test js file i run via the command "truffle test --network skaleTestBob test/erc721Test.test.js"  Note that I purposely send a token to a contract that is not erc721 deposit-enabled.  I know this will cause a reversion, but its the only way I'm able to reliably recreate the issue.  So if you run this same code on a local ganache-cli node it will of course revert but with the following expected error: "Error: Returned error: VM Exception while processing transaction: revert ERC721: transfer to non ERC721Receiver implementer -- Reason given: ERC721: transfer to non ERC721Receiver implementer."  Link to relevent github line. Now notice this error msg is different when run on the Bob testet. Somehow when run on Bob, the execution doesn't get to that line of solidity I linked to.  It seems to fail somewhere prior to that  in the safeTransferFom() function.  I can also get this error to sometimes occur even if the var addr1 is set to a random non-contract address such as the commented line there.  Uncomment that line (and remove the other addr1 definition) and it will perhaps pass on a ganache node but not on Bob:

const ERC721Mintable = artifacts.require('ERC721Mintable')

contract("ERC721", async accounts => {
it("sends an ERC721 token", async () => {
    let erc721Instance = await ERC721Mintable.deployed()

```
let addr1 = '0xf9cb8AA1C041E41459de4c296e55B30DB3FCe406'  //random address to send to
```

```
//let addr1 = erc721Instance.address //purposely set to deployed contract address to cause reversion
```

```
await erc721Instance.safeTransferFrom(accounts[0], addr1, 0)
```

```
let addr2 = await erc721Instance.ownerOf(0)
```

```
assert.equal(
addr1,
addr2,
'Transfer failed'
)
```

})
})

Here is the solidity i have written. It's located in contracts/Erc721Mintable.sol. It imports the standard openzeppelin contracts as seen on their github.

//SPDX-License-Identifier: MIT
pragma solidity 0.6.10;
import "/home/cartosys/openzeppelin-contracts/contracts/token/ERC721/ERC721.sol"; 
import "/home/cartosys/openzeppelin-contracts/contracts/utils/Counters.sol"; 
contract ERC721Mintable is IERC721Metadata, IERC721Enumerable,  ERC721 {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIds;

```
constructor(address userAddress, string memory name, string memory symbol) ERC721(name, symbol) public {
    uint256 newItemId = _tokenIds.current();
    _safeMint(userAddress, newItemId);
}
```

```
function mint(address to, string memory tokenURI) public returns (uint256) {
    _tokenIds.increment();
    uint256 newItemId = _tokenIds.current();
    _safeMint(to, newItemId);
    _setTokenURI(newItemId, tokenURI);
    return newItemId;
}
```

}

I have no problems doing safeTransferFrom() using erc20. And all of my other 70+ tests using my custom smart contracts & other standard ones work fine, FYI. 

That was long. :sweat_smile:  Let me know if anything needs clarification.
Thanks,
-b

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-3829)

**Comment by dimalit** [comment]
I'm investigating the issue, locally this test works fine, will check server configuration issues then.

**Comment by christineRPM** [comment]
I've reset the community test chain community configurations to clear the data and use the latest SAKLED build. We will check to see if the issue still persists.

**Comment by dimalit** [comment]
Looks like after server reset everything should work, please check!

**Comment by cartosys** [comment]
Verified on my end. The test now works!

`Using network 'skaleTestBob'.

*************************************************************************
ERC721 Address: 0x928144b8c808C4901f467254a171C8a90D0E910a
*************************************************************************

  Contract: ERC721
    ✓ sends an ERC721 token (1456ms)

  1 passing (2s)
`

Thank you for the quick turnaround!
